include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    unused_import: warning
    missing_required_param: warning
    missing_return: warning
    dead_code: warning
    prefer_const_constructors: true
