name: medi_link
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  appstrax_services: ^0.1.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  google_sign_in: ^7.1.1
  intl: ^0.20.2
  liquid_glass_renderer: ^0.1.1-dev.10
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoRB.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logoRB.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logoRB.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logoRB.png"

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
flutter_intl:
  enabled: true
